apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "restore.name" . }}
  labels: {{- include "restore.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
